portal:
  destination:
    # Destination types: SPAWN, HOME, BED, CUSTOM
    type: HOME
    # Teleports player to this location ONLY if type is set to CUSTOM
    custom:
      world: world
      x: 0
      y: 100
      z: 0
      yaw: 0
      pitch: 0