# All portal related configuration
portal:
  item:
    # Portal item display name
    name: "&5&lPortal"
    # Valid materials: SNOWBALL, ENDER_PEARL, EGG
    material: ENDER_PEARL
    # Portal item lore
    lore:
      - "&7Right click to throw portal"
  # Duration a portal will stay open for before it disappears.
  duration: 5
  # Should a portal disappear countdown should be sent to player.
  countdown: true
  # Portal destination configuration
  destination:
    # Destination types: SPAWN, HOME, BED, CUSTOM
    type: BED
    # Teleports player to this location ONLY if type is set to CUSTOM
    custom:
      world: world
      x: 0
      y: 100
      z: 0
      yaw: 0
      pitch: 0