name: PortaPortal
version: '${project.version}'
main: me.modify.portaportal.PortaPortal
api-version: '1.21'
depend: [WorldEdit]
authors: [modify]
description: Throwable portal items to teleport players to different locations.
