name: PortaPortal
version: 1.0.1
main: me.modify.portaportal.PortaPortal
api-version: '1.16'
depend: [WorldEdit]
softdepend: [Essentials]
authors: [modify]
description: Throwable portal items to teleport players to different locations.
